/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CategoriesRouteRouteImport } from './routes/categories/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesTrendingRouteImport } from './routes/categories/trending'
import { Route as CategoriesElectronicsRouteImport } from './routes/categories/electronics'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/_auth/signin/index'

const CategoriesRouteRoute = CategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRouteRoute,
} as any)
const CategoriesTrendingRoute = CategoriesTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => CategoriesRouteRoute,
} as any)
const CategoriesElectronicsRoute = CategoriesElectronicsRouteImport.update({
  id: '/electronics',
  path: '/electronics',
  getParentRoute: () => CategoriesRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/categories/electronics': typeof CategoriesElectronicsRoute
  '/categories/trending': typeof CategoriesTrendingRoute
  '/categories/': typeof CategoriesIndexRoute
  '/signin/': typeof AuthSigninIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/electronics': typeof CategoriesElectronicsRoute
  '/categories/trending': typeof CategoriesTrendingRoute
  '/categories': typeof CategoriesIndexRoute
  '/signin': typeof AuthSigninIndexRoute
  '/signup': typeof AuthSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/categories/electronics': typeof CategoriesElectronicsRoute
  '/categories/trending': typeof CategoriesTrendingRoute
  '/categories/': typeof CategoriesIndexRoute
  '/_auth/signin/': typeof AuthSigninIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/categories/electronics'
    | '/categories/trending'
    | '/categories/'
    | '/signin/'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories/electronics'
    | '/categories/trending'
    | '/categories'
    | '/signin'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/categories'
    | '/categories/electronics'
    | '/categories/trending'
    | '/categories/'
    | '/_auth/signin/'
    | '/_auth/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CategoriesRouteRoute: typeof CategoriesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
    '/categories/trending': {
      id: '/categories/trending'
      path: '/trending'
      fullPath: '/categories/trending'
      preLoaderRoute: typeof CategoriesTrendingRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
    '/categories/electronics': {
      id: '/categories/electronics'
      path: '/electronics'
      fullPath: '/categories/electronics'
      preLoaderRoute: typeof CategoriesElectronicsRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signin/': {
      id: '/_auth/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CategoriesRouteRouteChildren {
  CategoriesElectronicsRoute: typeof CategoriesElectronicsRoute
  CategoriesTrendingRoute: typeof CategoriesTrendingRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteRouteChildren: CategoriesRouteRouteChildren = {
  CategoriesElectronicsRoute: CategoriesElectronicsRoute,
  CategoriesTrendingRoute: CategoriesTrendingRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteRouteWithChildren = CategoriesRouteRoute._addFileChildren(
  CategoriesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CategoriesRouteRoute: CategoriesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
